# Generated by Django 3.2.4 on 2021-07-05 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=500)),
                ('domain', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('apply_by', models.DateField(null=True)),
                ('sal', models.FloatField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('skills', models.TextField(max_length=500)),
                ('domain', models.CharField(max_length=100)),
                ('about_comp', models.TextField(max_length=500)),
                ('about_work', models.TextField(max_length=500)),
                ('cgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('live_kt', models.CharField(choices=[('1', '1'), ('0', '0'), ('6', '6'), ('5', '5'), ('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=15, null=True)),
                ('drop', models.CharField(choices=[('2', '2'), ('1', '1'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True)),
                ('who_can_apply', models.TextField(max_length=500)),
                ('perks', models.TextField(max_length=500)),
                ('additional', models.TextField(max_length=500)),
                ('status', models.CharField(default=0, max_length=10, null=True)),
                ('work_from_home', models.BooleanField(default=False)),
                ('adm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.admindma')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('father_name', models.CharField(max_length=50, null=True)),
                ('skills', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('te_sem5_sgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('te_sem6_sgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('te_cgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('kt_TE', models.CharField(choices=[('1', '1'), ('0', '0'), ('6', '6'), ('5', '5'), ('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=15, null=True)),
                ('drop_TE', models.CharField(choices=[('2', '2'), ('1', '1'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True)),
                ('roll_no_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='SE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_sem3_sgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('se_sem4_sgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('se_cgpa', models.FloatField()),
                ('kt_SE', models.CharField(choices=[('1', '1'), ('0', '0'), ('6', '6'), ('5', '5'), ('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=15, null=True)),
                ('drop_SE', models.CharField(choices=[('2', '2'), ('1', '1'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True)),
                ('roll_no_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Mock_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('details', models.TextField(max_length=500)),
                ('link', models.CharField(default='https', max_length=50)),
                ('adm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.admindma')),
            ],
        ),
        migrations.CreateModel(
            name='Job_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.job')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Intership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('apply_by', models.DateField()),
                ('sal', models.IntegerField()),
                ('skills', models.TextField(max_length=500)),
                ('duration', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('about_comp', models.TextField(max_length=500)),
                ('about_work', models.TextField(max_length=500)),
                ('who_can_apply', models.TextField(max_length=500)),
                ('perks', models.TextField(max_length=500)),
                ('additional', models.TextField(max_length=500)),
                ('work_from_home', models.BooleanField(default=False)),
                ('adm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.admindma')),
            ],
        ),
        migrations.CreateModel(
            name='Int_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('int_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.intership')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='FE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fe_sem1_sgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('fe_sem2_sgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('fe_cgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('kt_FE', models.CharField(choices=[('1', '1'), ('0', '0'), ('6', '6'), ('5', '5'), ('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=15, null=True)),
                ('roll_no_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='BE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_sem7_sgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('be_sem8_sgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('be_cgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('kt_BE', models.CharField(choices=[('1', '1'), ('0', '0'), ('6', '6'), ('5', '5'), ('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=15, null=True)),
                ('drop_BE', models.CharField(choices=[('2', '2'), ('1', '1'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True)),
                ('roll_no_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Add_exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('rollNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Add_edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('10', '10th'), ('12', '12th'), ('diploma', 'Diploma')], max_length=50, null=True)),
                ('board', models.CharField(max_length=50)),
                ('percentage', models.FloatField()),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('marks', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('gap', models.CharField(choices=[('2', '2'), ('1', '1'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True)),
                ('diploma_pattern', models.CharField(choices=[('NA', 'NA'), ('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20)),
                ('diploma_aggregate_mw', models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(100)])),
                ('diploma_aggregate_pw', models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(100)])),
                ('no_of_dead_kt', models.CharField(max_length=10)),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
    ]
