# Generated by Django 3.2.4 on 2021-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('12', '12th'), ('10', '10th'), ('diploma', 'Diploma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('yearly pattern', 'yearly pattern'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('1', '1'), ('7', 'Greater than 6'), ('4', '4'), ('3', '3'), ('6', '6'), ('5', '5'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('1', '1'), ('7', 'Greater than 6'), ('4', '4'), ('3', '3'), ('6', '6'), ('5', '5'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('1', '1'), ('7', 'Greater than 6'), ('4', '4'), ('3', '3'), ('6', '6'), ('5', '5'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('1', '1'), ('7', 'Greater than 6'), ('4', '4'), ('3', '3'), ('6', '6'), ('5', '5'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('1', '1'), ('7', 'Greater than 6'), ('4', '4'), ('3', '3'), ('6', '6'), ('5', '5'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
    ]
