# Generated by Django 3.2.5 on 2021-07-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('yearly pattern', 'yearly pattern'), ('NA', 'NA'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
    ]
