# Generated by Django 3.2.5 on 2021-09-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='placed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern'), ('NA', 'NA')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='domain',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Banking', 'Banking'), ('Design', 'Design'), ('EduTech', 'EduTech'), ('Electrical Manufacturing', 'Electrical Manufacturing'), ('Financial Services', 'Financial Services'), ('Health Care', 'Health Care'), ('Information Technology', 'Information Technology'), ('Logistics & Supply Chain', 'Logistics & Supply Chain'), ('Management Consulting', 'Management Consulting'), ('Manufacturing', 'Manufacturing'), ('Marketing & Advertising', 'Marketing & Advertising'), ('Media Production', 'Media Production'), ('Professional Services', 'Professional Services'), ('Retail', 'Retail'), ('Telecommunications', 'Telecommunications')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_graduation',
            field=models.CharField(db_index=True, max_length=4, null=True),
        ),
    ]
