# Generated by Django 3.2.4 on 2021-06-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='skill',
            new_name='skills',
        ),
    ]
