# Generated by Django 3.2.4 on 2021-07-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('12', '12th'), ('10', '10th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('yearly pattern', 'yearly pattern'), ('NA', 'NA'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('2', '2'), ('5', '5'), ('3', '3'), ('1', '1'), ('0', '0'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('6', '6'), ('4', '4'), ('0', '0'), ('2', '2'), ('3', '3'), ('7', 'Greater than 6'), ('1', '1'), ('5', '5')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('6', '6'), ('4', '4'), ('0', '0'), ('2', '2'), ('3', '3'), ('7', 'Greater than 6'), ('1', '1'), ('5', '5')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('2', 'EXTC'), ('3', 'ETRX'), ('1', 'INFT'), ('4', 'BIOM'), ('0', 'CMPN')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('1', 'B'), ('2', 'C'), ('0', 'A')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('2', 'Other'), ('1', 'Female')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop',
            field=models.CharField(choices=[('2', '2'), ('5', '5'), ('3', '3'), ('1', '1'), ('0', '0'), ('4', '4')], max_length=15, null=True),
        ),
    ]
