<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-11 09:13
=======
# Generated by Django 3.2.4 on 2021-07-11 08:53
>>>>>>> 0352d7fb371e717e8bfa2f4021be15cccc7e6fbb

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
<<<<<<< HEAD
            field=models.CharField(choices=[('yearly pattern', 'yearly pattern'), ('NA', 'NA'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
=======
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('NA', 'NA'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
>>>>>>> 0352d7fb371e717e8bfa2f4021be15cccc7e6fbb
        ),
    ]
