# Generated by Django 3.2.5 on 2021-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_user',
            name='is_mail_send',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern'), ('NA', 'NA')], default='NA', max_length=20),
        ),
    ]
