# Generated by Django 3.2.4 on 2021-07-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('10', '10th'), ('diploma', 'Diploma'), ('12', '12th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('NA', 'NA'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('3', 'Greater than 2'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('3', 'Greater than 2'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('0', '0'), ('5', '5'), ('2', '2'), ('4', '4'), ('1', '1'), ('6', '6'), ('3', '3'), ('7', 'Greater than 6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('0', '0'), ('5', '5'), ('2', '2'), ('4', '4'), ('1', '1'), ('6', '6'), ('3', '3'), ('7', 'Greater than 6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('3', 'Greater than 2'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('0', '0'), ('5', '5'), ('2', '2'), ('4', '4'), ('1', '1'), ('6', '6'), ('3', '3'), ('7', 'Greater than 6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='drop_SE',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('3', 'Greater than 2'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('0', '0'), ('5', '5'), ('2', '2'), ('4', '4'), ('1', '1'), ('6', '6'), ('3', '3'), ('7', 'Greater than 6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop_TE',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('3', 'Greater than 2'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('0', '0'), ('5', '5'), ('2', '2'), ('4', '4'), ('1', '1'), ('6', '6'), ('3', '3'), ('7', 'Greater than 6')], max_length=15, null=True),
        ),
    ]
