# Generated by Django 3.2.4 on 2021-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0002_auto_20210707_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('12', '12th'), ('diploma', 'Diploma'), ('10', '10th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('NA', 'NA'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('1', '1'), ('5', '5'), ('0', '0'), ('4', '4'), ('2', '2'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('1', '1'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('1', '1'), ('5', '5'), ('0', '0'), ('6', '6'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('1', '1'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('1', '1'), ('5', '5'), ('0', '0'), ('6', '6'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('1', 'INFT'), ('2', 'EXTC'), ('0', 'CMPN'), ('3', 'ETRX'), ('4', 'BIOM')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'Other'), ('0', 'Male')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('5', '5'), ('0', '0'), ('4', '4'), ('2', '2'), ('3', '3')], max_length=15, null=True),
        ),
    ]
