# Generated by Django 3.2.4 on 2021-07-06 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0002_auto_20210706_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('10', '10th'), ('12', '12th'), ('diploma', 'Diploma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('1', '1'), ('7', 'Greater than 6'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6'), ('0', '0'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('1', '1'), ('7', 'Greater than 6'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6'), ('0', '0'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('1', '1'), ('7', 'Greater than 6'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6'), ('0', '0'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('1', '1'), ('7', 'Greater than 6'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6'), ('0', '0'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('1', '1'), ('7', 'Greater than 6'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6'), ('0', '0'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=500)),
                ('domain', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='documents/')),
                ('certificate_issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
    ]
