# Generated by Django 3.2.5 on 2021-08-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0002_alter_add_edu_diploma_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_no',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pan_card_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_no',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
