# Generated by Django 3.2.5 on 2021-07-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0002_auto_20210711_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('yearly pattern', 'yearly pattern'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('0', '0'), ('2', '2'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('5', '5'), ('0', '0'), ('3', '3'), ('1', '1'), ('6', '6'), ('7', 'Greater than 6'), ('4', '4'), ('2', '2')], max_length=15, null=True),
        ),
    ]
