# Generated by Django 3.2.4 on 2021-07-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0002_auto_20210712_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cgpa',
        ),
        migrations.AddField(
            model_name='job',
            name='aggregate_sgpi',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hsc_d_percentage',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ssc_percentage',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('yearly pattern', 'yearly pattern'), ('NA', 'NA'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
    ]
