# Generated by Django 3.2.4 on 2021-07-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0002_auto_20210705_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('12', '12th'), ('10', '10th'), ('diploma', 'Diploma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_aggregate_mw',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_aggregate_pw',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('NA', 'NA'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('1', '1'), ('3', '3'), ('2', '2'), ('7', 'Greater than 6'), ('4', '4'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('1', '1'), ('3', '3'), ('2', '2'), ('7', 'Greater than 6'), ('4', '4'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('1', '1'), ('3', '3'), ('2', '2'), ('7', 'Greater than 6'), ('4', '4'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='drop_SE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('1', '1'), ('3', '3'), ('2', '2'), ('7', 'Greater than 6'), ('4', '4'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop_TE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('1', '1'), ('3', '3'), ('2', '2'), ('7', 'Greater than 6'), ('4', '4'), ('0', '0')], max_length=15, null=True),
        ),
    ]
