# Generated by Django 3.2.4 on 2021-06-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0003_rename_perk_job_perks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock_test',
            name='link',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
