# Generated by Django 3.2.5 on 2021-07-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0003_auto_20210711_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_email_verified',
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('NA', 'NA'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('3', 'Greater than 2'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('4', '4'), ('0', '0'), ('2', '2'), ('3', '3'), ('1', '1'), ('7', 'Greater than 6'), ('5', '5'), ('6', '6')], max_length=15, null=True),
        ),
    ]
