<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-07-22 14:42
=======
# Generated by Django 3.2.5 on 2021-07-22 15:16
>>>>>>> 530cb0f5d43580e222e36013411136f18aba8397

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('DMS_Student', '0003_auto_20210712_1933'),
=======
        ('DMS_Student', '0003_alter_add_edu_diploma_pattern'),
>>>>>>> 530cb0f5d43580e222e36013411136f18aba8397
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
<<<<<<< HEAD
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('NA', 'NA'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
=======
            field=models.CharField(choices=[('yearly pattern', 'yearly pattern'), ('NA', 'NA'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
>>>>>>> 530cb0f5d43580e222e36013411136f18aba8397
        ),
    ]
