<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-06-14 16:26
=======
# Generated by Django 3.2.4 on 2021-06-14 16:45
>>>>>>> 2a4355872234131ca305659bd9f05242b5d763a1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0003_rename_perk_job_perks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock_test',
            name='link',
<<<<<<< HEAD
            field=models.CharField(default=None, max_length=50),
=======
            field=models.CharField(blank=True, max_length=50, null=True),
>>>>>>> 2a4355872234131ca305659bd9f05242b5d763a1
        ),
    ]
