# Generated by Django 3.2.5 on 2021-09-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0003_auto_20210916_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('yearly pattern', 'yearly pattern'), ('NA', 'NA'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.URLField(null=True),
        ),
    ]
