# Generated by Django 3.2.4 on 2021-07-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_edu',
            old_name='marks',
            new_name='percentage',
        ),
        migrations.AddField(
            model_name='add_edu',
            name='board',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
