# Generated by Django 3.2.4 on 2021-07-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0003_auto_20210707_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('10', '10th'), ('12', '12th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('1', '1'), ('5', '5'), ('4', '4'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('1', '1'), ('0', '0'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('0', '0'), ('7', 'Greater than 6'), ('5', '5'), ('4', '4'), ('6', '6'), ('1', '1'), ('3', '3'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('1', '1'), ('0', '0'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('0', '0'), ('7', 'Greater than 6'), ('5', '5'), ('4', '4'), ('6', '6'), ('1', '1'), ('3', '3'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('2', 'EXTC'), ('1', 'INFT'), ('0', 'CMPN'), ('4', 'BIOM'), ('3', 'ETRX')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('2', 'C'), ('1', 'B'), ('0', 'A')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female'), ('2', 'Other')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('1', '1'), ('5', '5'), ('4', '4'), ('2', '2')], max_length=15, null=True),
        ),
    ]
