# Generated by Django 3.2.4 on 2021-07-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0003_auto_20210705_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('yearly pattern', 'yearly pattern'), ('NA', 'NA'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='no_of_dead_kt',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('0', '0'), ('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('6', '6'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('0', '0'), ('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('6', '6'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('0', '0'), ('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('6', '6'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='drop_SE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('0', '0'), ('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('6', '6'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop_TE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('0', '0'), ('7', 'Greater than 6'), ('2', '2'), ('3', '3'), ('6', '6'), ('1', '1')], max_length=15, null=True),
        ),
    ]
