# Generated by Django 3.2.5 on 2021-09-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0003_auto_20210916_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='board',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='sal',
            field=models.CharField(max_length=150),
        ),
    ]
