# Generated by Django 3.2.4 on 2021-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0004_auto_20210711_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_edu',
            name='no_of_subject',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
