# Generated by Django 3.2.4 on 2021-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0004_alter_add_edu_diploma_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern'), ('NA', 'NA')], default='NA', max_length=20),
        ),
    ]
