# Generated by Django 3.2.4 on 2021-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0004_auto_20210707_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('10', '10th'), ('12', '12th'), ('diploma', 'Diploma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('yearly pattern', 'yearly pattern'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('3', '3'), ('5', '5'), ('2', '2'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('0', '0'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('6', '6'), ('5', '5'), ('2', '2'), ('3', '3'), ('7', 'Greater than 6'), ('1', '1'), ('0', '0'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('0', '0'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('6', '6'), ('5', '5'), ('2', '2'), ('3', '3'), ('7', 'Greater than 6'), ('1', '1'), ('0', '0'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('2', 'EXTC'), ('4', 'BIOM'), ('3', 'ETRX'), ('1', 'INFT'), ('0', 'CMPN')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('1', 'B'), ('0', 'A'), ('2', 'C')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('2', 'Other'), ('1', 'Female'), ('0', 'Male')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('3', '3'), ('5', '5'), ('2', '2'), ('4', '4')], max_length=15, null=True),
        ),
    ]
