# Generated by Django 3.2.4 on 2021-07-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0004_auto_20210705_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('10', '10th'), ('12', '12th'), ('diploma', 'Diploma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('3', '3'), ('0', '0'), ('1', '1'), ('2', '2'), ('5', '5'), ('6', '6'), ('7', 'Greater than 6'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('3', '3'), ('0', '0'), ('1', '1'), ('2', '2'), ('5', '5'), ('6', '6'), ('7', 'Greater than 6'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('3', '3'), ('0', '0'), ('1', '1'), ('2', '2'), ('5', '5'), ('6', '6'), ('7', 'Greater than 6'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='drop_SE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('3', '3'), ('0', '0'), ('1', '1'), ('2', '2'), ('5', '5'), ('6', '6'), ('7', 'Greater than 6'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop_TE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('3', '3'), ('0', '0'), ('1', '1'), ('2', '2'), ('5', '5'), ('6', '6'), ('7', 'Greater than 6'), ('4', '4')], max_length=15, null=True),
        ),
    ]
