# Generated by Django 3.2.5 on 2021-09-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0004_auto_20210918_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern'), ('NA', 'NA')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_graduation',
            field=models.CharField(db_index=True, max_length=4, null=True),
        ),
    ]
