<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-06-14 16:28
=======
# Generated by Django 3.2.4 on 2021-06-14 16:48
>>>>>>> 2a4355872234131ca305659bd9f05242b5d763a1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0004_mock_test_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mock_test',
            name='link',
<<<<<<< HEAD
            field=models.CharField(default='None', max_length=50),
=======
            field=models.CharField(default='https', max_length=50),
>>>>>>> 2a4355872234131ca305659bd9f05242b5d763a1
        ),
    ]
