# Generated by Django 3.2.5 on 2021-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0004_alter_add_edu_diploma_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
        migrations.AddField(
            model_name='job',
            name='year',
            field=models.CharField(default=2021, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern'), ('NA', 'NA')], default='NA', max_length=20),
        ),
    ]
