# Generated by Django 3.2.4 on 2021-07-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0004_auto_20210706_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('12', '12th'), ('10', '10th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('yearly pattern', 'yearly pattern'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('0', '0'), ('7', 'Greater than 6'), ('3', '3'), ('4', '4'), ('5', '5'), ('1', '1'), ('2', '2'), ('6', '6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('0', '0'), ('7', 'Greater than 6'), ('3', '3'), ('4', '4'), ('5', '5'), ('1', '1'), ('2', '2'), ('6', '6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('0', '0'), ('7', 'Greater than 6'), ('3', '3'), ('4', '4'), ('5', '5'), ('1', '1'), ('2', '2'), ('6', '6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='drop_SE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('0', '0'), ('7', 'Greater than 6'), ('3', '3'), ('4', '4'), ('5', '5'), ('1', '1'), ('2', '2'), ('6', '6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop_TE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('0', '0'), ('7', 'Greater than 6'), ('3', '3'), ('4', '4'), ('5', '5'), ('1', '1'), ('2', '2'), ('6', '6')], max_length=15, null=True),
        ),
    ]
