# Generated by Django 3.2.5 on 2021-07-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0004_auto_20210711_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_email_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('yearly pattern', 'yearly pattern'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('0', '0'), ('3', 'Greater than 2'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('2', '2'), ('0', '0'), ('5', '5'), ('1', '1'), ('7', 'Greater than 6'), ('3', '3'), ('4', '4'), ('6', '6')], max_length=15, null=True),
        ),
    ]
