# Generated by Django 3.2.4 on 2021-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0004_auto_20210701_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('diploma', 'DIPLOMA'), ('10', '10th'), ('12', '12th')], max_length=50),
        ),
    ]
