# Generated by Django 3.2.5 on 2021-10-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0005_auto_20210925_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(null=True, upload_to='Resume/'),
        ),
    ]
