# Generated by Django 3.2.4 on 2021-07-06 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0005_auto_20210706_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fe',
            name='kt_FE',
        ),
        migrations.RemoveField(
            model_name='se',
            name='drop_SE',
        ),
        migrations.RemoveField(
            model_name='se',
            name='kt_SE',
        ),
        migrations.RemoveField(
            model_name='te',
            name='drop_TE',
        ),
        migrations.RemoveField(
            model_name='te',
            name='kt_TE',
        ),
        migrations.AddField(
            model_name='student',
            name='aadhar_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('4', 'BIOM'), ('1', 'INFT'), ('0', 'CMPN'), ('3', 'ETRX'), ('2', 'EXTC')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='co_curriculum_activities',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='corresponding_address',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='disability',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('2', 'C'), ('1', 'B'), ('0', 'A')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='extra_curriculum_activities',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('2', 'Other'), ('1', 'Female')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkdin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='other',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pan_card_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='student',
            name='residence_phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='type_of_disability',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='te',
            name='dead_kt',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='te',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('4', '4'), ('5', '5'), ('0', '0'), ('2', '2'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='te',
            name='live_kt',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('10', '10th'), ('diploma', 'Diploma'), ('12', '12th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('1', '1'), ('4', '4'), ('5', '5'), ('0', '0'), ('2', '2'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('1', '1'), ('3', 'Greater than 2'), ('0', '0'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('1', '1'), ('6', '6'), ('4', '4'), ('5', '5'), ('0', '0'), ('2', '2'), ('7', 'Greater than 6'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('3', 'Greater than 2'), ('0', '0'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('1', '1'), ('6', '6'), ('4', '4'), ('5', '5'), ('0', '0'), ('2', '2'), ('7', 'Greater than 6'), ('3', '3')], max_length=15, null=True),
        ),
    ]
