# Generated by Django 3.2.4 on 2021-07-07 14:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0005_auto_20210707_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fe_sgpa1', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('fe_sgpa2', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('fe_cgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('se_sgpa3', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('se_sgpa4', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('se_cgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('te_sgpa5', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('te_sgpa6', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('te_cgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('be_sgpa7', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('be_sgpa8', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('be_cgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('live_kt', models.CharField(choices=[('1', '1'), ('2', '2'), ('6', '6'), ('4', '4'), ('7', 'Greater than 6'), ('3', '3'), ('0', '0'), ('5', '5')], max_length=15, null=True)),
                ('dead_kt', models.CharField(choices=[('1', '1'), ('2', '2'), ('6', '6'), ('4', '4'), ('7', 'Greater than 6'), ('3', '3'), ('0', '0'), ('5', '5')], max_length=15, null=True)),
                ('drop', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fe',
            name='roll_no_1',
        ),
        migrations.RemoveField(
            model_name='se',
            name='roll_no_2',
        ),
        migrations.RemoveField(
            model_name='te',
            name='roll_no_3',
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('12', '12th'), ('10', '10th'), ('diploma', 'Diploma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('yearly pattern', 'yearly pattern'), ('NA', 'NA'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('2', '2'), ('0', '0'), ('5', '5'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Greater than 2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('6', '6'), ('4', '4'), ('7', 'Greater than 6'), ('3', '3'), ('0', '0'), ('5', '5')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('0', 'CMPN'), ('4', 'BIOM'), ('1', 'INFT'), ('2', 'EXTC'), ('3', 'ETRX')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('2', 'Other'), ('0', 'Male'), ('1', 'Female')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='BE',
        ),
        migrations.DeleteModel(
            name='FE',
        ),
        migrations.DeleteModel(
            name='SE',
        ),
        migrations.DeleteModel(
            name='TE',
        ),
        migrations.AddField(
            model_name='curredu',
            name='roll_no_curr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student'),
        ),
    ]
