# Generated by Django 3.2.4 on 2021-06-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0006_alter_mock_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mock_test',
            name='link',
        ),
    ]
