# Generated by Django 3.2.4 on 2021-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0006_auto_20210706_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_of_graduation',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('12', '12th'), ('diploma', 'Diploma'), ('10', '10th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('NA', 'NA'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('4', '4'), ('2', '2'), ('5', '5'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('0', '0'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('3', '3'), ('7', 'Greater than 6'), ('6', '6'), ('5', '5'), ('1', '1'), ('0', '0'), ('4', '4'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('0', '0'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('3', '3'), ('7', 'Greater than 6'), ('6', '6'), ('5', '5'), ('1', '1'), ('0', '0'), ('4', '4'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('4', 'BIOM'), ('0', 'CMPN'), ('1', 'INFT'), ('3', 'ETRX'), ('2', 'EXTC')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('2', 'Other'), ('1', 'Female'), ('0', 'Male')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('4', '4'), ('2', '2'), ('5', '5'), ('1', '1')], max_length=15, null=True),
        ),
    ]
