# Generated by Django 3.2.4 on 2021-06-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0007_remove_mock_test_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mock_test',
        ),
    ]
