# Generated by Django 3.2.4 on 2021-07-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0007_auto_20210707_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('4', '4'), ('1', '1'), ('0', '0'), ('5', '5')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='dead_kt',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('1', '1'), ('6', '6'), ('7', 'Greater than 6'), ('2', '2'), ('0', '0'), ('5', '5')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='drop',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='live_kt',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('1', '1'), ('6', '6'), ('7', 'Greater than 6'), ('2', '2'), ('0', '0'), ('5', '5')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('1', '1'), ('6', '6'), ('7', 'Greater than 6'), ('2', '2'), ('0', '0'), ('5', '5')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('1', 'INFT'), ('2', 'EXTC'), ('3', 'ETRX'), ('4', 'BIOM'), ('0', 'CMPN')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('2', 'C'), ('1', 'B'), ('0', 'A')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('2', 'Other'), ('1', 'Female')], max_length=15, null=True),
        ),
    ]
