# Generated by Django 3.2.4 on 2021-07-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0008_auto_20210707_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('12', '12th'), ('10', '10th'), ('diploma', 'Diploma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('1', '1'), ('5', '5'), ('3', '3'), ('4', '4'), ('0', '0'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='dead_kt',
            field=models.CharField(choices=[('7', 'Greater than 6'), ('3', '3'), ('0', '0'), ('2', '2'), ('6', '6'), ('1', '1'), ('5', '5'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('0', '0'), ('3', 'Greater than 2'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='live_kt',
            field=models.CharField(choices=[('7', 'Greater than 6'), ('3', '3'), ('0', '0'), ('2', '2'), ('6', '6'), ('1', '1'), ('5', '5'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('0', '0'), ('3', 'Greater than 2'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('7', 'Greater than 6'), ('3', '3'), ('0', '0'), ('2', '2'), ('6', '6'), ('1', '1'), ('5', '5'), ('4', '4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('3', 'ETRX'), ('4', 'BIOM'), ('2', 'EXTC'), ('0', 'CMPN'), ('1', 'INFT')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('1', 'B'), ('0', 'A'), ('2', 'C')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('2', 'Other'), ('1', 'Female'), ('0', 'Male')], max_length=15, null=True),
        ),
    ]
