# Generated by Django 3.2.4 on 2021-06-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0008_delete_mock_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('date', models.DateField()),
                ('link', models.CharField(default='None', max_length=50)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('details', models.TextField(max_length=500)),
                ('adm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.admindma')),
            ],
        ),
    ]
