# Generated by Django 3.2.5 on 2021-12-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0008_auto_20211208_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='who_can_apply',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='year',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_graduation',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
