# Generated by Django 3.2.4 on 2021-07-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0009_auto_20210707_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('10', '10th'), ('diploma', 'Diploma'), ('12', '12th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('yearly pattern', 'yearly pattern'), ('semester pattern', 'semester pattern'), ('NA', 'NA')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[(5, '5 years'), (4, '4 years'), (0, '0 year'), (2, '2 years'), (1, '1 year'), (3, '3 years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='dead_kt',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='drop',
            field=models.CharField(choices=[(5, '5 years'), (4, '4 years'), (0, '0 year'), (2, '2 years'), (1, '1 year'), (3, '3 years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='live_kt',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('1', '1'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('4', '4'), ('7', 'Greater than 6'), ('0', '0'), ('3', '3'), ('2', '2'), ('6', '6'), ('1', '1'), ('5', '5')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[(0, 'INFT'), (2, 'EXTC'), (1, 'CMPN'), (3, 'ETRX'), (4, 'BIOM')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('1', 'B'), ('2', 'C'), ('0', 'A')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[(1, 'Female'), (2, 'Other'), (0, 'Male')], max_length=15, null=True),
        ),
    ]
