# Generated by Django 3.2.5 on 2021-12-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0008_auto_20211208_1257'),
        ('DMS_Student', '0009_auto_20211208_1242'),
    ]

    operations = [
    ]
