# Generated by Django 3.2.4 on 2021-07-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0009_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_exp',
            old_name='roll_no',
            new_name='rollNo',
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('10', '10th'), ('diploma', 'Diploma'), ('12', '12th')], max_length=50, null=True),
        ),
    ]
