# Generated by Django 3.2.4 on 2021-07-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0010_auto_20210702_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('10', '10th'), ('12', '12th'), ('diploma', 'Diploma')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('te_sem1_sgpa', models.FloatField()),
                ('te_sem2_sgpa', models.FloatField()),
                ('te_cgpa', models.FloatField()),
                ('roll_no_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='SE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_sem1_sgpa', models.FloatField()),
                ('se_sem2_sgpa', models.FloatField()),
                ('se_cgpa', models.FloatField()),
                ('roll_no_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='FE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fe_sem1_sgpa', models.FloatField()),
                ('fe_sem2_sgpa', models.FloatField()),
                ('fe_cgpa', models.FloatField()),
                ('roll_no_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='BE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_sem1_sgpa', models.FloatField()),
                ('be_sem2_sgpa', models.FloatField()),
                ('be_cgpa', models.FloatField()),
                ('roll_no_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS_Student.student')),
            ],
        ),
    ]
