# Generated by Django 3.2.4 on 2021-06-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0010_alter_mock_test_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
    ]
