# Generated by Django 3.2.4 on 2021-07-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0010_auto_20210707_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('12', '12th'), ('10', '10th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('yearly pattern', 'yearly pattern'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[(0, '0 year'), (1, '1 year'), (4, '4 years'), (2, '2 years'), (3, '3 years'), (5, '5 years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='drop',
            field=models.CharField(choices=[(0, '0 year'), (1, '1 year'), (2, '2 years'), (3, '3 years'), (4, '4 years'), (5, '5 years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('1', '1'), ('6', '6'), ('0', '0'), ('3', '3'), ('2', '2'), ('4', '4'), ('5', '5'), ('7', 'Greater than 6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[(1, 'CMPN'), (2, 'EXTC'), (4, 'BIOM'), (3, 'ETRX'), (0, 'INFT')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('1', 'B'), ('0', 'A'), ('2', 'C')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[(2, 'Other'), (1, 'Female'), (0, 'Male')], max_length=15, null=True),
        ),
    ]
