# Generated by Django 3.2.4 on 2021-07-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0011_auto_20210702_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='be',
            old_name='be_sem1_sgpa',
            new_name='be_sem7_sgpa',
        ),
        migrations.RenameField(
            model_name='be',
            old_name='be_sem2_sgpa',
            new_name='be_sem8_sgpa',
        ),
        migrations.RenameField(
            model_name='se',
            old_name='se_sem1_sgpa',
            new_name='se_sem3_sgpa',
        ),
        migrations.RenameField(
            model_name='se',
            old_name='se_sem2_sgpa',
            new_name='se_sem4_sgpa',
        ),
        migrations.RenameField(
            model_name='te',
            old_name='te_sem1_sgpa',
            new_name='te_sem5_sgpa',
        ),
        migrations.RenameField(
            model_name='te',
            old_name='te_sem2_sgpa',
            new_name='te_sem6_sgpa',
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('12', '12th'), ('10', '10th')], max_length=50, null=True),
        ),
    ]
