# Generated by Django 3.2.5 on 2021-12-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0011_remove_student_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='placed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('yearly pattern', 'yearly pattern'), ('semester pattern', 'semester pattern'), ('NA', 'NA')], default='NA', max_length=20),
        ),
    ]
