# Generated by Django 3.2.4 on 2021-06-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0012_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='int_user',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
