# Generated by Django 3.2.4 on 2021-07-03 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0012_auto_20210702_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('12', '12th'), ('diploma', 'Diploma'), ('10', '10th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='be_cgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='be',
            name='be_sem7_sgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='be',
            name='be_sem8_sgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='fe',
            name='fe_cgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='fe',
            name='fe_sem1_sgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='fe',
            name='fe_sem2_sgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='se',
            name='se_sem3_sgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='se',
            name='se_sem4_sgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='te',
            name='te_cgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='te',
            name='te_sem5_sgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='te',
            name='te_sem6_sgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
