# Generated by Django 3.2.5 on 2021-12-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0012_auto_20211208_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern'), ('NA', 'NA')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_graduation',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
