# Generated by Django 3.2.4 on 2021-07-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0013_auto_20210707_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('yearly pattern', 'yearly pattern'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('5', '5'), ('1', '1'), ('0', '0'), ('3', '3'), ('7', 'Greater than 6'), ('4', '4'), ('6', '6'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(null=True, upload_to='Resume/'),
        ),
    ]
