# Generated by Django 3.2.4 on 2021-07-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0013_auto_20210703_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='intership',
            name='part_time_job',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intership',
            name='work_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='part_time_job',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('10', '10th'), ('diploma', 'Diploma'), ('12', '12th')], max_length=50, null=True),
        ),
    ]
