# Generated by Django 3.2.4 on 2021-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0014_auto_20210704_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intership',
            name='part_time_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='part_time_job',
            field=models.BooleanField(default=False),
        ),
    ]
