# Generated by Django 3.2.4 on 2021-07-07 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0014_auto_20210707_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='average_sgpi',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='total_grade',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('2', '2'), ('3', 'Greater than 2'), ('0', '0'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('6', '6'), ('2', '2'), ('7', 'Greater than 6'), ('4', '4'), ('1', '1'), ('5', '5'), ('3', '3'), ('0', '0')], max_length=15, null=True),
        ),
    ]
