# Generated by Django 3.2.4 on 2021-07-07 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0015_auto_20210707_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('yearly pattern', 'yearly pattern'), ('semester pattern', 'semester pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='be_cgpa',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='be_sgpi7',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='be_sgpi8',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='fe_cgpa',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='fe_sgpi1',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='fe_sgpi2',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='se_cgpa',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='se_sgpi3',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='se_sgpi4',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='te_cgpa',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='te_sgpi5',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='te_sgpi6',
            field=models.FloatField(default='NA', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('3', '3'), ('7', 'Greater than 6'), ('2', '2'), ('0', '0'), ('6', '6'), ('1', '1')], max_length=15, null=True),
        ),
    ]
