# Generated by Django 3.2.4 on 2021-06-30 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DMS_Student', '0015_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, default='de', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intership',
            name='link',
            field=models.URLField(max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
