# Generated by Django 3.2.4 on 2021-07-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0015_auto_20210704_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intership',
            name='part_time_job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='part_time_job',
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('12', '12th'), ('10', '10th')], max_length=50, null=True),
        ),
    ]
