# Generated by Django 3.2.4 on 2021-06-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0016_auto_20210701_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='intership',
            name='link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
