# Generated by Django 3.2.4 on 2021-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0016_auto_20210707_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('NA', 'NA'), ('semester pattern', 'semester pattern'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('2', '2'), ('3', 'Greater than 2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('5', '5'), ('2', '2'), ('3', '3'), ('0', '0'), ('4', '4'), ('6', '6'), ('7', 'Greater than 6'), ('1', '1')], max_length=15, null=True),
        ),
    ]
