# Generated by Django 3.2.4 on 2021-07-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0017_auto_20210707_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('NA', 'NA'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='be_cgpa',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='be_sgpi7',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='be_sgpi8',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='drop',
            field=models.CharField(choices=[('0', '0 year'), ('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('5', '5 years')], default='0', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='fe_cgpa',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='fe_sgpi1',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='fe_sgpi2',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='se_cgpa',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='se_sgpi3',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='se_sgpi4',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='te_cgpa',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='te_sgpi5',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='te_sgpi6',
            field=models.CharField(default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('7', 'Greater than 6'), ('0', '0'), ('3', '3'), ('5', '5'), ('6', '6'), ('4', '4')], max_length=15, null=True),
        ),
    ]
