# Generated by Django 3.2.4 on 2021-07-05 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0017_alter_add_edu_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cgpa',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('Greater than 2', 3), ('1', 1), ('2', 2)], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('1', 1), ('4', 4), ('Greater than 6', 7), ('5', 5), ('3', 3), ('6', 6), ('2', 2)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('12', '12th'), ('diploma', 'Diploma'), ('10', '10th')], max_length=50, null=True),
        ),
    ]
