# Generated by Django 3.2.4 on 2021-06-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0018_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
