# Generated by Django 3.2.4 on 2021-07-05 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0019_auto_20210705_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('12', '12th'), ('diploma', 'Diploma'), ('10', '10th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('2', 2), ('0', 0), ('1', 1), ('Greater than 2', 3)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('2', 2), ('1', 1), ('0', 0), ('5', 5), ('4', 4), ('6', 6), ('3', 3), ('Greater than 6', 7)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='sal',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
