# Generated by Django 3.2.4 on 2021-07-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0019_auto_20210707_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curredu',
            old_name='be_cgpa',
            new_name='cgpa1',
        ),
        migrations.RenameField(
            model_name='curredu',
            old_name='be_sgpi7',
            new_name='cgpa2',
        ),
        migrations.RenameField(
            model_name='curredu',
            old_name='be_sgpi8',
            new_name='cgpa3',
        ),
        migrations.RenameField(
            model_name='curredu',
            old_name='fe_cgpa',
            new_name='cgpa4',
        ),
        migrations.RenameField(
            model_name='curredu',
            old_name='fe_sgpi1',
            new_name='sgpi1',
        ),
        migrations.RenameField(
            model_name='curredu',
            old_name='fe_sgpi2',
            new_name='sgpi2',
        ),
        migrations.RenameField(
            model_name='curredu',
            old_name='se_cgpa',
            new_name='sgpi3',
        ),
        migrations.RenameField(
            model_name='curredu',
            old_name='se_sgpi3',
            new_name='sgpi4',
        ),
        migrations.RenameField(
            model_name='curredu',
            old_name='se_sgpi4',
            new_name='sgpi5',
        ),
        migrations.RenameField(
            model_name='curredu',
            old_name='te_cgpa',
            new_name='sgpi6',
        ),
        migrations.RenameField(
            model_name='curredu',
            old_name='te_sgpi5',
            new_name='sgpi7',
        ),
        migrations.RenameField(
            model_name='curredu',
            old_name='te_sgpi6',
            new_name='sgpi8',
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('2', '2'), ('3', 'Greater than 2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('1', '1'), ('7', 'Greater than 6'), ('5', '5'), ('2', '2'), ('0', '0'), ('6', '6')], max_length=15, null=True),
        ),
    ]
