# Generated by Django 3.2.4 on 2021-07-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0019_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
