# Generated by Django 3.2.4 on 2021-07-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0020_auto_20210705_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('Greater than 2', 3), ('2', 2), ('0', 0), ('1', 1)], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('Greater than 2', 3), ('2', 2), ('0', 0), ('1', 1)], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('2', 2), ('3', 3), ('4', 4), ('1', 1), ('0', 0), ('Greater than 6', 7), ('6', 6), ('5', 5)], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('2', 2), ('3', 3), ('4', 4), ('1', 1), ('0', 0), ('Greater than 6', 7), ('6', 6), ('5', 5)], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='se',
            name='drop_FE',
            field=models.CharField(choices=[('Greater than 2', 3), ('2', 2), ('0', 0), ('1', 1)], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('2', 2), ('3', 3), ('4', 4), ('1', 1), ('0', 0), ('Greater than 6', 7), ('6', 6), ('5', 5)], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='te',
            name='drop_TE',
            field=models.CharField(choices=[('Greater than 2', 3), ('2', 2), ('0', 0), ('1', 1)], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('2', 2), ('3', 3), ('4', 4), ('1', 1), ('0', 0), ('Greater than 6', 7), ('6', 6), ('5', 5)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('Greater than 2', 3), ('2', 2), ('0', 0), ('1', 1)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('2', 2), ('3', 3), ('4', 4), ('1', 1), ('0', 0), ('Greater than 6', 7), ('6', 6), ('5', 5)], max_length=15, null=True),
        ),
    ]
