# Generated by Django 3.2.4 on 2021-07-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0020_auto_20210707_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('yearly pattern', 'yearly pattern'), ('semester pattern', 'semester pattern'), ('NA', 'NA')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='curredu',
            name='drop',
            field=models.CharField(choices=[('0 year', '0 year'), ('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 years'), ('4 years', '4 years'), ('5 years', '5 years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('3', 'Greater than 2'), ('2', '2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('0', '0'), ('6', '6'), ('1', '1'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('7', 'Greater than 6')], max_length=15, null=True),
        ),
    ]
