# Generated by Django 3.2.4 on 2021-06-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0020_alter_student_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
    ]
