# Generated by Django 3.2.4 on 2021-07-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0021_auto_20210705_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('12', '12th'), ('10', '10th'), ('diploma', 'Diploma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('3', 'Greater than 2'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('3', 'Greater than 2'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('3', 3), ('5', 5), ('6', 6), ('Greater than 6', 7), ('2', 2), ('1', 1), ('0', 0), ('4', 4)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('3', 3), ('5', 5), ('6', 6), ('Greater than 6', 7), ('2', 2), ('0', '0'), ('4', 4), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('0', 0), ('2', 2), ('1', 1), ('Greater than 2', 3)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('3', 3), ('5', 5), ('6', 6), ('Greater than 6', 7), ('2', 2), ('1', 1), ('0', 0), ('4', 4)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='drop_FE',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('3', 'Greater than 2'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('2', '2'), ('5', '5'), ('0', '0'), ('7', 'Greater than 6'), ('6', '6'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop_TE',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('3', 'Greater than 2'), ('1', '1')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('3', 3), ('5', 5), ('6', 6), ('Greater than 6', 7), ('2', 2), ('1', 1), ('0', 0), ('4', 4)], max_length=15, null=True),
        ),
    ]
