# Generated by Django 3.2.4 on 2021-07-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0021_auto_20210705_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('12', '12th'), ('10', '10th'), ('diploma', 'Diploma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('1', '1'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('1', '1'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('7', 'Greater than 6'), ('2', '2'), ('6', '6'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('7', 'Greater than 6'), ('2', '2'), ('6', '6'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('1', '1'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('7', 'Greater than 6'), ('2', '2'), ('6', '6'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='drop_FE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('1', '1'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('7', 'Greater than 6'), ('2', '2'), ('6', '6'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop_TE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('1', '1'), ('2', '2'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('7', 'Greater than 6'), ('2', '2'), ('6', '6'), ('0', '0')], max_length=15, null=True),
        ),
    ]
