# Generated by Django 3.2.4 on 2021-07-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0022_auto_20210705_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='se',
            name='drop_FE',
        ),
        migrations.AddField(
            model_name='se',
            name='drop_SE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('12', '12th'), ('10', '10th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('5', '5'), ('0', '0'), ('3', '3'), ('4', '4'), ('2', '2'), ('7', 'Greater than 6'), ('1', '1'), ('6', '6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('5', '5'), ('0', '0'), ('3', '3'), ('4', '4'), ('2', '2'), ('7', 'Greater than 6'), ('1', '1'), ('6', '6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('5', '5'), ('0', '0'), ('3', '3'), ('4', '4'), ('2', '2'), ('7', 'Greater than 6'), ('1', '1'), ('6', '6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('5', '5'), ('0', '0'), ('3', '3'), ('4', '4'), ('2', '2'), ('7', 'Greater than 6'), ('1', '1'), ('6', '6')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop_TE',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('0', '0'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('5', '5'), ('0', '0'), ('3', '3'), ('4', '4'), ('2', '2'), ('7', 'Greater than 6'), ('1', '1'), ('6', '6')], max_length=15, null=True),
        ),
    ]
