# Generated by Django 3.2.4 on 2021-07-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0022_auto_20210705_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='degree',
            field=models.CharField(choices=[('10', '10th'), ('12', '12th'), ('diploma', 'Diploma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_edu',
            name='gap',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='drop_BE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='be',
            name='kt_BE',
            field=models.CharField(choices=[('7', 'Greater than 6'), ('2', '2'), ('6', '6'), ('1', '1'), ('4', '4'), ('0', '0'), ('5', '5'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fe',
            name='kt_FE',
            field=models.CharField(choices=[('7', 'Greater than 6'), ('2', '2'), ('6', '6'), ('1', '1'), ('4', '4'), ('0', '0'), ('5', '5'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('2', 2), ('0', 0), ('1', 1), ('Greater than 2', 3)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('0', 0), ('5', 5), ('3', 3), ('2', 2), ('4', 4), ('6', 6), ('Greater than 6', 7), ('1', 1)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='drop_FE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='kt_SE',
            field=models.CharField(choices=[('7', 'Greater than 6'), ('2', '2'), ('6', '6'), ('1', '1'), ('4', '4'), ('0', '0'), ('5', '5'), ('3', '3')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='drop_TE',
            field=models.CharField(choices=[('3', 'Greater than 2'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='te',
            name='kt_TE',
            field=models.CharField(choices=[('7', 'Greater than 6'), ('2', '2'), ('6', '6'), ('1', '1'), ('4', '4'), ('0', '0'), ('5', '5'), ('3', '3')], max_length=15, null=True),
        ),
    ]
