# Generated by Django 3.2.4 on 2021-06-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0022_student_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
