# Generated by Django 3.2.4 on 2021-07-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0023_auto_20210708_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edu',
            name='diploma_pattern',
            field=models.CharField(choices=[('semester pattern', 'semester pattern'), ('NA', 'NA'), ('yearly pattern', 'yearly pattern')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='drop',
            field=models.CharField(choices=[('1', '1'), ('0', '0'), ('2', '2'), ('3', 'Greater than 2')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='live_kt',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('2', '2'), ('1', '1'), ('3', '3'), ('7', 'Greater than 6'), ('6', '6'), ('5', '5')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('BIOM', 'BIOM'), ('CMPN', 'CMPN'), ('ETRX', 'ETRX'), ('EXTC', 'EXTC'), ('INFT', 'INFT')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=12, null=True),
        ),
    ]
