# Generated by Django 3.2.4 on 2021-06-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0030_alter_student_roll_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(max_length=150),
        ),
    ]
