# Generated by Django 3.2.4 on 2021-06-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0032_auto_20210701_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='int_user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='job_user',
            name='date',
        ),
    ]
