# Generated by Django 3.2.4 on 2021-06-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0033_auto_20210701_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='int_user',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job_user',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
