# Generated by Django 3.2.4 on 2021-06-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_Student', '0019_delete_login'),
        ('DMS_Student', '0034_auto_20210701_0021'),
    ]

    operations = [
    ]
